# H2
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:~/test
    driver-class-name: org.h2.Driver
# Datasource
  h2:
    console:
      enabled: false
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
  application:
    name: "Payment Service"

swagger:
  service:
    version: "0.0.1"
    title: ${spring.application.name}
    description: "This is a simple API"
    termsPath: ""
    email: "noreply@example.com"
    licenceType: ""
    licencePath: ""

info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Payments API
  contact:
    email: someone@example.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html