# H2
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
# Datasource
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true

swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Payments API
  contact:
    email: pedro.aguiar@globant.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html